export const DUMMY = {
  "device": {
      "id": "f945a888360e9506336588d92704edd52f979eeb",
      "is_active": true,
      "is_private_session": false,
      "is_restricted": false,
      "name": "iPhone",
      "type": "Smartphone",
      "volume_percent": 100
  },
  "shuffle_state": false,
  "repeat_state": "off",
  "timestamp": 1680187366904,
  "context": {
      "external_urls": {
          "spotify": "https://open.spotify.com/collection/tracks"
      },
      "href": "https://api.spotify.com/v1/me/tracks",
      "type": "collection",
      "uri": "spotify:user:jay.14-ca:collection"
  },
  "progress_ms": 30198,
  "item": {
      "album": {
          "album_group": "album",
          "album_type": "album",
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/5WM5zPOswRcPu07rxP2dQv"
                  },
                  "href": "https://api.spotify.com/v1/artists/5WM5zPOswRcPu07rxP2dQv",
                  "id": "5WM5zPOswRcPu07rxP2dQv",
                  "name": "Hugh Laurie",
                  "type": "artist",
                  "uri": "spotify:artist:5WM5zPOswRcPu07rxP2dQv"
              }
          ],
          "available_markets": [
              "AE",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BW",
              "BY",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CM",
              "CV",
              "CW",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DZ",
              "EE",
              "EG",
              "ES",
              "ET",
              "FI",
              "FR",
              "GA",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GW",
              "HK",
              "HR",
              "HU",
              "ID",
              "IL",
              "IN",
              "IQ",
              "IT",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KM",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MD",
              "ME",
              "MG",
              "MK",
              "ML",
              "MO",
              "MR",
              "MU",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SN",
              "ST",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TR",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UZ",
              "VN",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "external_urls": {
              "spotify": "https://open.spotify.com/album/4cXN5lJTFaFFfzFWaihRfm"
          },
          "href": "https://api.spotify.com/v1/albums/4cXN5lJTFaFFfzFWaihRfm",
          "id": "4cXN5lJTFaFFfzFWaihRfm",
          "images": [
              {
                  "height": 640,
                  "url": "https://i.scdn.co/image/ab67616d0000b273d763bf549cb95f620834cb73",
                  "width": 640
              },
              {
                  "height": 300,
                  "url": "https://i.scdn.co/image/ab67616d00001e02d763bf549cb95f620834cb73",
                  "width": 300
              },
              {
                  "height": 64,
                  "url": "https://i.scdn.co/image/ab67616d00004851d763bf549cb95f620834cb73",
                  "width": 64
              }
          ],
          "is_playable": true,
          "name": "Let Them Talk",
          "release_date": "2011-04-18",
          "release_date_precision": "day",
          "total_tracks": 15,
          "type": "album",
          "uri": "spotify:album:4cXN5lJTFaFFfzFWaihRfm"
      },
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/5WM5zPOswRcPu07rxP2dQv"
              },
              "href": "https://api.spotify.com/v1/artists/5WM5zPOswRcPu07rxP2dQv",
              "id": "5WM5zPOswRcPu07rxP2dQv",
              "name": "Hugh Laurie",
              "type": "artist",
              "uri": "spotify:artist:5WM5zPOswRcPu07rxP2dQv"
          }
      ],
      "available_markets": [
          "AR",
          "AU",
          "AT",
          "BE",
          "BG",
          "CA",
          "CZ",
          "DK",
          "DE",
          "EE",
          "FI",
          "FR",
          "GR",
          "HK",
          "HU",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MX",
          "NL",
          "NZ",
          "NO",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "US",
          "LI",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AM",
          "BW",
          "BF",
          "CV",
          "CW",
          "GM",
          "GE",
          "GW",
          "LS",
          "LR",
          "MW",
          "ML",
          "NA",
          "NE",
          "ST",
          "SN",
          "SC",
          "SL",
          "TL",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "ET",
          "XK"
      ],
      "disc_number": 1,
      "duration_ms": 227600,
      "explicit": false,
      "external_ids": {
          "isrc": "GBAHT1100017"
      },
      "external_urls": {
          "spotify": "https://open.spotify.com/track/2HsUsb8EO0txxp62D9E1xT"
      },
      "href": "https://api.spotify.com/v1/tracks/2HsUsb8EO0txxp62D9E1xT",
      "id": "2HsUsb8EO0txxp62D9E1xT",
      "is_local": false,
      "name": "Battle of Jericho",
      "popularity": 30,
      "preview_url": "https://p.scdn.co/mp3-preview/b4fba2758ac675a1e3859dc3bd20cc6d5170f923?cid=f4b0e7da2ec04fd99c46162217b8af5b",
      "track_number": 5,
      "type": "track",
      "uri": "spotify:track:2HsUsb8EO0txxp62D9E1xT"
  },
  "currently_playing_type": "track",
  "actions": {
      "disallows": {
          "resuming": true,
          "skipping_prev": true
      }
  },
  "is_playing": true
}